name:                proskell
version:             0.1.0.0
github:              "transistorfet/proskell"
license:             GPL-3
author:              "transistor fet"
maintainer:          "trans@jabberwocky.ca"
copyright:           "2022 transistor fet"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/proskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  proskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proskell

tests:
  proskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proskell
